# Generated by Django 4.2.6 on 2023-10-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
