# Generated by Django 4.2.6 on 2023-10-11 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('help_request', '0002_helprequest_is_rejected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helprequest',
            old_name='is_rejected',
            new_name='is_declined',
        ),
        migrations.AddField(
            model_name='helprequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
