# Generated by Django 4.2.6 on 2023-10-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_request', '0003_rename_is_rejected_helprequest_is_declined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='is_declined',
        ),
        migrations.AddField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Declined', 'Declined'), ('Approved', 'Approved'), ('In process', 'In process'), ('Completed', 'Completed')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6),
        ),
    ]
