# Generated by Django 4.2.6 on 2023-10-13 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help_request', '0005_alter_helprequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclinedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('declined_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='help_request.helprequest')),
            ],
        ),
    ]
