# Generated by Django 4.2.6 on 2023-10-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_request', '0006_declinedrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Declined', 'Declined'), ('For restoration', 'For restoration'), ('Approved', 'Approved'), ('In process', 'In process'), ('Completed', 'Completed')], default='Active', max_length=15),
        ),
    ]
